[package]
name = "pokeget"
author = "talwat"
version = "1.1.0"
edition = "2021"
description = "Display pokemon sprites in your terminal."
license-file = "LICENSE"
readme = "README.md"
documentation = "https://github.com/talwat/showie"
homepage = "https://github.com/talwat/showie"
repository = "https://github.com/talwat/showie"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = { version = "0.11.4", default-features = false }
clap = { version = "4.3.19", features = ["derive"] }
image = { version = "0.24.6", default-features = false, features = [
    "png",
    "rgb",
] }
rand = "0.8.5"
rust-embed = { version = "6.8.1", features = ["include-exclude"] }
showie = "1.0.0"
